JuliaGizmos/Blink.jl

src/AtomShell/process.jl
Changed how electron is called on linux in the `process.jl` file. Changed the call from `...../.julia/v0.4/Blink/deps/atom/atom` to `...../.julia/v0.4/Blink/deps/atom/electron`
Example:
```
juila> using Blink
julia> _shell = Blink.shell()
ERROR: could not spawn `/home/chase/.julia/v0.4/Blink/deps/atom/atom /home/chase/.julia/v0.4/Blink/src/AtomShell/main.js port 3371`: no such file or directory (ENOENT)
in _jl_spawn at process.jl:262
in anonymous at process.jl:415
in setup_stdio at process.jl:403
in spawn at process.jl:414
in init at /home/chase/.julia/v0.4/Blink/src/AtomShell/process.jl:61
in shell at /home/chase/.julia/v0.4/Blink/src/AtomShell/process.jl:102
in get_window at /home/chase/.julia/v0.4/Plotlyjs.jl/src/display.jl:45
in show at …
```
=> Change electron call.

src/AtomShell/window.jl
Note that since 
~~~julia
close(w) = @dot w close
~~~
depends on @ dot, I moved api.jl to AtomShell so @ dot is defined first.
Closes #28
=> Add a "close" method to the API

.travis.yml, test/runtests.jl
=> Added very very basic test

src/content/api.jl
Hi,
I've been working on using DevTools to add rendering support for `ThreeJS` from the REPL. ThreeJS uses [HTML Imports](https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports), and I added a function to add these HTML imports and the corresponding entry given a file in Blink. This PR adds a new exported function, `importhtml!` to add this functionality.
This would be useful for things like [ThreeJS](https://github.com/rohitvarkey/ThreeJS.jl), and [Escher](https://github.com/shashi/Escher.jl) which use web components.
I wasn't sure if I should add this to the `load!` function as users might expect it to load the HTML file rather than importing it, like what `loadhtml` does.
Regards,
Rohit
=> Add support for HTML imports

src/content/api.jl
Make use of https://github.com/JunoLab/Blink.jl/blob/master/res/blink.js#L33-L35 to block till HTML import has loaded properly. This is the default behavior of `<link rel="import" ..>` markup (I am not sure why the `appendChild` call does not block) and makes sure the components are loaded when you subsequently reference them.
cc @rohitvarkey
=> Make importhtml! synchronous

src/AtomShell/process.jl
Trivial change to the error message, but I temporarily tried to do `Pkg.add("AtomShell")` before realizing that it was an internal module to Blink
=> Be explicit about what to run if Electron not found

res/blink.js, src/AtomShell/main.js, src/content/server.jl, src/rpc/callbacks.jl
`m.type = t` would succeed when `m` is a `String`, however JSON.stringify serializes `m` as a string losing the type field.
This PR requires "type" and "data" field in every message
fixes #65
=> Fix bug in Blink.msg

src/content/server.jl
Error generated on closing of Window, with various error messages, one
being:
WARNING: the no-op `transpose` fallback is deprecated, and no more
specific `transpose` method for ArgumentError exists. Consider
`permutedims(x, [2, 1])` or writing a specific
`transpose(x::ArgumentError)` method if appropriate.
in ws_handler(::Dict{Any,Any}) at
/Users/lwabeke/.julia/v0.5/Blink/src/content/server.jl:45
=> Change to get rid of error on closing of Blink Window

src/content/api.jl, src/rpc/jsexprs.jl, test/runtests.jl
Disclaimer: This is a total shim/hack to get PlotlyJS.jl working on 0.6.
The issue is that the MacroTools `@match` rule 
```julia
d(xs__) => dict_expr(io, xs)
```
no longer works on 0.6.
See below:
```
julia> using MacroTools
julia> ex = :(Dict("name"=>"JSLoadError", "message"=>"failed to load "))
:(Dict("name" => "JSLoadError", "message" => "failed to load "))
julia> @match ex begin
Blink.d(xs__) => "found a dict"
Dict(xs___) => "call dict function"
_ => "nada"
end
"nada"
```
I instead need to match on the Expr where we call Dict.
```
julia> @match ex begin
Blink.d(xs__) => "found a dict"
x_Associative => "associative"
$(Expr(:call, :Dict, :__)) => "ugly expr call Dict"
_ => "nada"
end
"ugly expr call Dict"
```
So, what this does is catch that case and then hand off to a new …
=> BUG: try to fix bug with dict matching on 0.6

.travis.yml
'release' is 0.5 and I don't think we are supposed to use. In any case, this enables testing on 0.6.
=> Test on 0.6 and nightly. Allow failures on nightly

src/rpc/callbacks.jl
This seems necessary to get handlers to work properly. 
With this PR @Ward9250's code in #57 works properly:
```
using Blink
w = Window()
sleep(5)
body!(w, "My Fancy App!<br/><br/><button id='gobutton'>Click me!</button>")
handle(w, "press") do args
println(args)
end
@js_ w document.getElementById("gobutton").onclick = () -> Blink.msg("press", 122)
close(w)
```
Not sure if this is a good idea in general though -- feedback would be appreciated :)
=> invokelatest handler

res/blink.js, src/content/api.jl, test/api.jl, test/runtests.jl
Fixes #109.
Moves the fade/no-fade decision from Julia down into javascript, so that
more code can be reused whether or not `fade == true`.
This also simplifies the `content!` function body, which will make
fixing #108 a bit easier.
=> Always call `evalscripts` in `fill`.

src/AtomShell/install.jl
The version we're using is a bit old, in particular it suffers from [this issue](https://github.com/electron/electron/issues/9860) that was only fixed in 1.8.x
=> bump electron version

src/content/main.html, test/runtests.jl
It is needed for katex compatibility: https://techoverflow.net/2018/03/14/how-to-fix-katex-parse-error-katex-doesnt-work-in-quirks-mode/
~Not sure if the fix belongs here or in Mustache (it seems that Mustache does not create the `<!DOCTYPE html>` declaration).~
EDIT: @pfitzseb  somehow I hallucinated before and the simple fix you proposed does work (is the one in this PR)
=> add doctype html

test/AtomShell/window.jl
This was failing on `master`, I think because windows was refusing to allow the window to be so small.
=> Fix Appveyor Windows test failure: win was too small

res/blink.js, src/content/api.jl, test/content/api.jl
Adds an option, `async` to `body!()` and `content!()`, which when `true` will
give the old behavior (return immediately), but when false, will block until
the `Window` is finished `eval`ing the javascript statement to assign the new content.
Note that this blocks until `evalscripts` has been called for all new scripts,
but that if your scripts themselves do anything asynchronous, it won't wait for
them to finish.
--------
Right now, I have `async=true` by default so that this doesn't change the
current behavior, but I really think we should set this false by default! :) If
you want, we can merge it in like this, wait for it to soak in, make sure
everyone likes the change, etc, and then flip the switch?
That said, it _shouldn't_ break anyone's code to just flip the default, it will
just …
=> Make body!() and content!() synchronous.

.travis.yml, REQUIRE, appveyor.yml, deps/build.jl, src/AtomShell/AtomShell.jl, src/AtomShell/install.jl, src/AtomShell/main.js, src/AtomShell/process.jl, src/AtomShell/window.jl, src/Blink.jl, src/content/api.jl, src/content/config.jl, src/content/content.jl, src/content/server.jl, src/rpc/rpc.jl, test/AtomShell/window.jl, test/content/api.jl, test/runtests.jl
Includes #139 plus a few more deprecation fixes. Also now checks out WebIO.jl master on 0.7+
Fixes #132 
Fixes #145
=> Julia v0.7 support

test/runtests.jl
Test is broken on master, but this fixes it. It looks like we were broken by
this recent Mustache change:
https://github.com/jverzani/Mustache.jl/releases/tag/v0.5.0
=> Fix broken test: update test of Mustache token value

res/blink.js, src/AtomShell/window.jl, src/content/main.html, src/content/server.jl, src/rpc/rpc.jl, test/AtomShell/window.jl, test/content/api.jl, test/runtests.jl
This is the remaining part of #136: making window creation synchronous.
I've added an `:async` param to the dictionary options to create the window, and it will cause the function to block until the window is created, the `blink.js` javascript is loaded, and the WebSocket to communicate with julia is open.
-------------------
This PR definitely needs a design review. I haven't actually done much javascript development ever, so a lot of this was murky water for me. I think it works, but i'm not sure I did everything the best way.
Also, I set the default to be synchronous, with the optional `:async` flag. I think that's the right default value, but just like in #136, we should think about whether to flip it right away or roll this out somehow nicer. That said, I think probably it would be …
=> Add option to make creating a Window synchronous

src/content/config.jl
Currently, we use `haskey(ENV, "key") ? get(ENV, "key") : "default value"` which isn't a valid usage of `get` and thus results in an error whenever `BLINK_PORT` is set.
=> Fix incorrect get(ENV, ...)

src/rpc/rpc.jl
=> Add documentation for the @js functions and friends

deps/build.jl
`] build Blink` now installs Electron the first time, and any time the electron version is updated in the code but not in the installed version.
Closes https://github.com/JunoLab/Blink.jl/issues/170
=> Automatically install Electron when building Blink

.travis.yml
I think we broke travis a bit during the manual commits to master between #173 and  #176:
https://github.com/JunoLab/Blink.jl/compare/279797f..d428434
Looking at the latest builds, it doesn't seem to actually be running the tests! 😱
Also, we accidentally deleted the `after_success` `Coverage` section, so i've added that back. I'm still not sure what caused the Tests to stop running, but i'm looking into it!
=> Fix travis.yml to run tests & coverage after Documentation changes

src/AtomShell/install.jl
Ref. issue #148
modified:   src/AtomShell/install.jl
Use (julia)/bin/7z.exe for unpacking. This is not available in home-built Julia. If so, it looks for the latest binary download folder (assuming the installation was not made for all users).
Using home-built-Julia is a prerequisite to using > 4 cores, or due to a known bug, things like 
```
using Logging
@edit Logging.ConsoleLogger()
```
=> Use 7z.exe from Julia binary download

src/AtomShell/process.jl
=> stop extending nonexistent Base.quit

src/AtomShell/process.jl
A timeout of ~3 seconds is too quick when an X11 window is forwarded over SSH.  Yeah, Electron with a remote X11 window is pretty slow to use, but it's handy at times.  In my case, extending it to ~4 seconds was sufficient.  I've extended it to 5 seconds just to be safe for folks with slower connections.
=> Increase the try_connect timeout

src/AtomShell/window.jl, test/runtests.jl, test/webio.jl
I think the use of `Condition` over something like `Future` from `Distributed` (builtin package) was a mistake but trying to rectify that wouldn't be worth it right now (and I'm not sure that anyone else will agree with me on that haha).
Anyway, what this diff does:
* Makes `Window()` sync by default (so that anything you do with the resulting Window is safe).
* Adds `Base.wait(::Window)`. After this returns, the Window should be safe to do things to (e.g. `body!`).
* Window's that were initialized with a URL have no associated initialization and cannot be `wait`-ed (I'd rather raise an error that says what you're trying to do doesn't make sense than just silently allowing it).
If you try to do anything before `wait`ing the Window, I make no guarantees and I don't think Blink, in general, …
=> Fix WebIO integration, make Window's sync by default.

res/blink.css
The default background is white anyway. Forcing a white background messes up with Interact styling. Trying to have a dark style fails as inside the body the css set by Blink prevails (I don't understand the rules of css well enough to know why), see for example [this issue](https://github.com/JuliaGizmos/Interact.jl/issues/331#issue-478597259).
=> Do not force white background

README.md
It would also be good to trigger the CI to build the docs for `stable`
=> Fix travis badge link

src/AtomShell/install.jl
`unpack_cmd` is exported from BinDeps. Let them deal with the 7zip stuff, we don't need to do anything special in this package. Though we'll still be nice and try to point at a possible solution for Windows users that build from source.
This still uses `Base.UV_ENOENT`, which isn't exported, but it's a lot better than what we had before. Alternatively, we can use `BinDeps.exe7z` and directly check for its existence, but that isn't exported either and I expect `Base.UV_ENOENT` to be less likely to change.
=> Just use BinDeps.unpack_cmd instead of looking for 7zip ourselves

src/AtomShell/AtomShell.jl, src/AtomShell/process.jl
There are some parts of the Blink API that I'd like to change around a bit. I think there are parts that are "cludgy" and lead to some strange errors (à la #191).
If it's okay, I'd like to rework some parts of the API with the strategy of maintaining backward compatibility and with the end goal of possibly removing some of those deprecations and releasing a new major version.
This is related to the work I've been doing trying to [whip WebIO into shape](https://github.com/JuliaGizmos/WebIO.jl/issues/368). The end goal is to make everything in the JuliaGizmos universe work together more seamlessly.
=> Use Ref for active electron process, add some Base methods.

.travis.yml, appveyor.yml
This removes Julia 0.7 from TravisCI and Appveyor, and tests against Julia 1.0, 1.3, and nightly.
=> Remove Julia 0.7 tests.

docs/src/communication.md
Explain how to pass an array, and/or use argument destructuring, in order to pass multiple arguments to a handler.
Follow up to #237; fixes #222.
=> Improve documentation explaining passing multiple args in event handlers

src/AtomShell/webio.jl
Fixes https://github.com/JuliaGizmos/WebIO.jl/issues/357 and https://github.com/JuliaGizmos/Interact.jl/issues/344
I don't know why exactly, I'd like to know though if anyone knows the difference between `active(comm.window)`  and  `active(comm.window.content)`? Is there a possibility of deadlock or some other funny business if `active(comm.window)` is called from two different tasks/threads?
Nonetheless I think we should probably just merge this since:
a) this PR just restores the code from before the WebIO integration was moved here (and was probably just [accidentally](https://github.com/JuliaGizmos/Interact.jl/issues/344#issuecomment-612944016) changed then)
b) WebIO, and thus PlotlyJS, Interact, etc. are somewhat broken in Blink without this for more complex UIs (see linked issues) …
=> Don't check the Window, check the Page

.travis.yml, Project.toml, src/AtomShell/window.jl, src/rpc/rpc.jl
This should make tests pass on 1.6.
Enable testing on latest release
=> Updates macros to Julia 1.6 macro scoping

Project.toml, src/content/content.jl, src/content/server.jl
As HTTP package has support for web sockets now and the actual package WebSockets is having hard time to keep up with HTTP updates, why not simplify dependency  chain
=> remove dependency on WebSockets

src/AtomShell/window.jl, test/webio.jl
having to always do `body!(w, x)` is a little verbose. This PR  adds a keyword: `Window(; body=x)`
=> add `body` keyword to `Window`

src/content/main.html
After the first window, I found that the callback for window creation was being executed quickly enough that the `initwebio!(w)` method is triggered before the page has fully loaded (and hence before `webio` exists). Adding the [`defer` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#defer) to the `blink.js` script ensures it won't be executed until after the browser has had a chance to load in the `webio.bundled.js` package.
Fixes [Blink.jl#300](https://github.com/JuliaGizmos/Blink.jl/issues/300), [WebIO.jl#505](https://github.com/JuliaGizmos/WebIO.jl/issues/505), and [PlotlyJS.jl#460](https://github.com/JuliaPlots/PlotlyJS.jl/issues/460).
=> Delay execution of blink.js while document loads

src/AtomShell/process.jl, src/AtomShell/window.jl, src/content/server.jl
Fixes https://github.com/JuliaGizmos/Blink.jl/issues/317.
Added a new keyword argument to the `close(win)` function. Now, `close(win, quit=true)` shuts down the Mux/HTTP server and also closes the shell socket connection, allowing the electron process to shut down cleanly.
=> add option to close server and end electron process
